name: hc-frontend-workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Build docker image
        run: docker build -t aravsanj/hackerconnect-frontend .
      - name: Publish image to docker hub
        run: docker push aravsanj/hackerconnect-frontend:latest

  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Pull image from docker hub
        run: docker pull aravsanj/hackerconnect-fontend:latest
      - name: Delete old container
        run: docker rm -f hackerconnect-frontend-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name hackerconnect-frontend-container aravsanj/hackerconnect-frontend
